-- auto-generated definition
create table ictrp.ictrp_full_weekly_data
(
    trialid                        varchar,
    "(No column name)"             varchar,
    secondaryids                   varchar,
    public_title                   varchar,
    scientific_title               varchar,
    url                            varchar,
    public_contact_firstname       varchar,
    public_contact_lastname        varchar,
    public_contact_address         varchar,
    public_contact_email           varchar,
    public_contact_tel             varchar,
    public_contact_affiliation     varchar,
    scientific_contact_firstname   varchar,
    scientific_contact_lastname    varchar,
    scientific_contact_address     varchar,
    scientific_contact_email       varchar,
    scientific_contact_tel         varchar,
    scientific_contact_affiliation varchar,
    study_type                     varchar,
    study_design                   varchar,
    phase                          varchar,
    date_registration              varchar,
    date_enrollement               varchar,
    target_size                    varchar,
    recruitment_status             varchar,
    primary_sponsor                varchar,
    secondary_sponsors             varchar,
    source_support                 varchar,
    countries                      varchar,
    conditions                     varchar,
    interventions                  varchar,
    age_min                        varchar,
    age_max                        varchar,
    gender                         varchar,
    inclusion_criteria             varchar,
    exclusion_criteria             varchar,
    primary_outcome                varchar,
    secondary_outcomes             varchar,
    bridging_flag                  varchar,
    bridged_type                   varchar,
    childs                         varchar,
    type_enrolment                 varchar,
    retrospective_flag             varchar,
    results_actual_enrollment      varchar,
    results_url_link               varchar,
    results_summary                varchar,
    results_date_posted            varchar,
    results_date_first_publication varchar,
    results_baseline_char          varchar,
    results_participant_flow       varchar,
    results_adverse_events         varchar,
    results_outcome_measures       varchar,
    results_url_protocol           varchar,
    results_ipd_plan               varchar,
    results_ipd_description        varchar,
    results_date_completed         varchar,
    results_yes_no                 varchar,
    ethics_status                  varchar,
    ethics_approval_date           varchar,
    ethics_contact_name            varchar,
    ethics_contact_address         varchar,
    ethics_contact_phone           varchar,
    ethics_contact_email           varchar
);


